### ISSUE TITLE
Add readme on how to generate the docs locally

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/docs#47]
I cannot generate the docs locally:
```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: No such file or directory
make: *** [html] Error 1
```

**Comment by cmodijk** [comment]
I used `$ make autobuild` in the past but my machine is broken at the moment will look into it this weekend.

**Comment by cmodijk** [comment]
Fixed my machine and `$ make html` and `$ make autobuild` both work did you install the `pip install -r requirements.txt` ?

**Comment by ruudk** [comment]
Yep I did :(
