### ISSUE TITLE
[Asynchronous example] Consuming Messages - Cronjob

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/docs#7]
I missed the last section of your `Asynchronous example` while i was reviewing it. But the last part is not something i would suggest running in a cronjob. The `rabbitmq:consume` is a command that never stops running and keeps consuming messages. If there is no message there it just waits ontil there is a new message to consume. So if you configure this every minute than you will end up with a new worker every minute. We run this commands using `supervisord`.
* http://docs.simplebus.io/en/latest/Introduction/asynchronous-example.html#consuming-messages

**Comment by Nyholm** [comment]
Thank you. I did not know. (Not using that command.)

I'll update
